### ISSUE TITLE
Page layout behaves badly for small window sizes

### ISSUE THREAD

**Issue by wetneb** [wetneb/dissemin#74]

**Comment by a3nm** [comment]
Tried to push a fix https://github.com/wetneb/dissemin/commit/e0fdb33259ca590a6498208047d79d8fbada3a6c for the front page.

**Comment by wetneb** [comment]
Fixed for the splash page, not for the dynamic part of the website, but hey…

**Comment by a3nm** [comment]
Still a problem: on orcid.dissemin.in, when resizing the page to a narrow width, the header should not stop when scrolling right. Same on ens.dissem.in. Should be fixable with http://stackoverflow.com/a/32299854/

**Comment by wetneb** [comment]
This has been fixed by p4bl0-, right? Feel free to close this :) .

**Comment by p4bl0-** [comment]
Oh right. Closing.
